// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:hoppit_app/core/config/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Env.firebaseWebApiKey,
    appId: '1:998336177148:web:77dea6844498c72e738879',
    messagingSenderId: '998336177148',
    projectId: 'hoppit-qa',
    authDomain: 'hoppit-qa.firebaseapp.com',
    storageBucket: 'hoppit-qa.firebasestorage.app',
    measurementId: 'G-M4WN0WVPSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Env.firebaseAndroidApiKey,
    appId: '1:998336177148:android:cbf0d0a1bc97fd0e738879',
    messagingSenderId: '998336177148',
    projectId: 'hoppit-qa',
    storageBucket: 'hoppit-qa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.firebaseIosApiKey,
    appId: '1:998336177148:ios:6e56558e834a2125738879',
    messagingSenderId: '998336177148',
    projectId: 'hoppit-qa',
    storageBucket: 'hoppit-qa.firebasestorage.app',
    iosBundleId: 'com.example.hoppitApp',
  );
}
